export const CUSTOM_BACKENDS = [
  'default',
  'cuda',
  'tensorrt',
  'directml',
  'ncnn',
] as const;

export const CUSTOM_BACKEND_LABELS: Record<(typeof CUSTOM_BACKENDS)[number], string> = {
  default: 'AUTO',
  cuda: 'CUDA',
  tensorrt: 'TENSORRT',
  directml: 'DIRECTML',
  ncnn: 'NCNN',
};

// NOTE: These lists are kept in sync with src/utils/argumentsChecker.py.
// We add a UI-only sentinel 'custom' option at the end where applicable.

export const INTERPOLATE_METHODS = [
  'distildrba',
  'distildrba-lite',
  'distildrba-lite-tensorrt',
  'rife4.6',
  'rife4.15-lite',
  'rife4.16-lite',
  'rife4.17',
  'rife4.18',
  'rife4.20',
  'rife4.21',
  'rife4.22',
  'rife4.22-lite',
  'rife4.25',
  'rife4.25-lite',
  'rife4.25-heavy',
  'rife-ncnn',
  'rife4.6-ncnn',
  'rife4.15-lite-ncnn',
  'rife4.16-lite-ncnn',
  'rife4.17-ncnn',
  'rife4.18-ncnn',
  'rife4.20-ncnn',
  'rife4.21-ncnn',
  'rife4.22-ncnn',
  'rife4.22-lite-ncnn',
  'rife4.6-tensorrt',
  'rife4.15-tensorrt',
  'rife4.17-tensorrt',
  'rife4.18-tensorrt',
  'rife4.20-tensorrt',
  'rife4.21-tensorrt',
  'rife4.22-tensorrt',
  'rife4.22-lite-tensorrt',
  'rife4.25-tensorrt',
  'rife4.25-lite-tensorrt',
  'rife4.25-heavy-tensorrt',
  'rife-tensorrt',
  'gmfss',
  'gmfss-tensorrt',
  'rife_elexor',
  'rife_elexor-tensorrt',
  'rife4.6-directml',
  'custom',
] as const;

export const UPSCALE_METHODS = [
  'shufflecugan',
  'fallin_soft',
  'fallin_soft-tensorrt',
  'fallin_soft-directml',
  'fallin_strong',
  'fallin_strong-tensorrt',
  'fallin_strong-directml',
  'compact',
  'ultracompact',
  'superultracompact',
  'span',
  'compact-directml',
  'ultracompact-directml',
  'superultracompact-directml',
  'shufflespan-directml',
  'span-directml',
  'shufflecugan-ncnn',
  'span-ncnn',
  'compact-tensorrt',
  'ultracompact-tensorrt',
  'superultracompact-tensorrt',
  'span-tensorrt',
  'shufflecugan-tensorrt',
  'shufflespan-tensorrt',
  'open-proteus',
  'open-proteus-tensorrt',
  'open-proteus-directml',
  'aniscale2',
  'aniscale2-tensorrt',
  'aniscale2-directml',
  'rtmosr',
  'rtmosr-tensorrt',
  'rtmosr-directml',
  'saryn',
  'saryn-tensorrt',
  'saryn-directml',
  'animesr',
  'animesr-tensorrt',
  'animesr-directml',
  'gauss',
  'gauss-tensorrt',
  'gauss-directml',
  'gauss-openvino',
  'compact-openvino',
  'ultracompact-openvino',
  'superultracompact-openvino',
  'span-openvino',
  'open-proteus-openvino',
  'aniscale2-openvino',
  'shufflespan-openvino',
  'rtmosr-openvino',
  'saryn-openvino',
  'fallin_soft-openvino',
  'fallin_strong-openvino',
  'custom',
] as const;

export const RESTORE_METHODS = [
  'scunet',
  'scunet-tensorrt',
  'scunet-directml',
  'nafnet',
  'dpir',
  'real-plksr',
  'anime1080fixer',
  'anime1080fixer-tensorrt',
  'anime1080fixer-directml',
  'fastlinedarken',
  'fastlinedarken-tensorrt',
  'gater3',
  'gater3-directml',
  'codeformer-tensorrt',
  'codeformer-directml',
  'deh264_real',
  'deh264_real-tensorrt',
  'deh264_real-directml',
  'deh264_span',
  'deh264_span-tensorrt',
  'deh264_span-directml',
  'hurrdeblur',
  'hurrdeblur-tensorrt',
  'hurrdeblur-directml',
  'custom',
] as const;

export const SCENECHANGE_METHODS = [
  'maxxvit-tensorrt',
  'maxxvit-directml',
  'differential',
  'differential-tensorrt',
  'shift_lpips-tensorrt',
  'shift_lpips-directml',
] as const;

export const DEPTH_METHODS = [
  'small_v2',
  'base_v2',
  'large_v2',
  'giant_v2',
  'distill_small_v2',
  'distill_base_v2',
  'distill_large_v2',
  'og_small_v2',
  'og_base_v2',
  'og_large_v2',
  'og_giant_v2',
  'og_distill_small_v2',
  'og_distill_base_v2',
  'og_distill_large_v2',
  'og_video_small_v2',
  'small_v2-tensorrt',
  'base_v2-tensorrt',
  'large_v2-tensorrt',
  'distill_small_v2-tensorrt',
  'distill_base_v2-tensorrt',
  'distill_large_v2-tensorrt',
  'small_v2-directml',
  'base_v2-directml',
  'large_v2-directml',
  'distill_small_v2-directml',
  'distill_base_v2-directml',
  'distill_large_v2-directml',
  'og_small_v2-tensorrt',
  'og_base_v2-tensorrt',
  'og_large_v2-tensorrt',
  'og_distill_small_v2-tensorrt',
  'og_distill_base_v2-tensorrt',
  'og_distill_large_v2-tensorrt',
  'small_v3',
  'base_v3',
  'large_v3',
  'giant_v3',
  'small_v3-directml',
  'base_v3-directml',
  'large_v3-directml',
  'giant_v3-directml',
  'small_v3-tensorrt',
  'base_v3-tensorrt',
  'large_v3-tensorrt',
  'giant_v3-tensorrt',
  'custom',
] as const;

export const ENCODE_METHODS = [
  'x264',
  'slow_x264',
  'x264_10bit',
  'x264_animation',
  'x264_animation_10bit',
  'x265',
  'slow_x265',
  'x265_10bit',
  'nvenc_h264',
  'slow_nvenc_h264',
  'nvenc_h265',
  'slow_nvenc_h265',
  'nvenc_h265_10bit',
  'nvenc_av1',
  'slow_nvenc_av1',
  'qsv_h264',
  'qsv_h265',
  'qsv_h265_10bit',
  'av1',
  'slow_av1',
  'h264_amf',
  'hevc_amf',
  'hevc_amf_10bit',
  'prores',
  'prores_segment',
  'gif',
  'vp9',
  'qsv_vp9',
  'lossless',
  'lossless_nvenc',
  'png',
] as const;

// These are UI-only lists (Python doesn't publish a canonical list here).
export const SEGMENT_METHODS = [
  'anime',
  'anime-tensorrt',
  'anime-directml',
  'cartoon',
  'custom',
] as const;

export const DEDUP_METHODS = [
  'ssim',
  'ssim-cuda',
  'mse',
  'mse-cuda',
  'flownets',
  'vmaf',
  'vmaf-cuda',
] as const;

export const OBJ_DETECT_METHODS = [
  'yolov9_small-directml',
  'yolov9_medium-directml',
  'yolov9_large-directml',
  'yolov9_small-openvino',
  'yolov9_medium-openvino',
  'yolov9_large-openvino',
] as const;
